/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MySwing.togglebutton;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Arturo
 */
public class MitogglebuttonJF extends javax.swing.JFrame {

    /**
     * Creates new form MitogglebuttonJF
     */
    public MitogglebuttonJF() {
        initComponents();
        
        ImageIcon image = new ImageIcon("C:\\Users\\Arturo\\Downloads\\focoapagado1.png");
        jLabel1.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbtnPrenderApagar = new javax.swing.JToggleButton();
        lblToggle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbtnPrenderApagar.setText("Click");
        tbtnPrenderApagar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbtnPrenderApagarStateChanged(evt);
            }
        });
        tbtnPrenderApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPrenderApagarActionPerformed(evt);
            }
        });

        lblToggle.setForeground(new java.awt.Color(51, 51, 51));
        lblToggle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblToggle.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(tbtnPrenderApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(lblToggle)
                .addGap(18, 18, 18)
                .addComponent(tbtnPrenderApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnPrenderApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPrenderApagarActionPerformed

    boolean estado =  tbtnPrenderApagar.isSelected();
   
    System.out.println(estado);
    
    if(estado){
        lblToggle.setText("Foco Encendido");
 
     ImageIcon image = new ImageIcon("C:\\Users\\Arturo\\Downloads\\focoencendido1.png");
        jLabel1.setIcon(image);
    }else{
        ImageIcon image = new ImageIcon("C:\\Users\\Arturo\\Downloads\\focoapagado1.png");
        jLabel1.setIcon(image);
    }
        
        
        
    }//GEN-LAST:event_tbtnPrenderApagarActionPerformed

    private void tbtnPrenderApagarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbtnPrenderApagarStateChanged
 

        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnPrenderApagarStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MitogglebuttonJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MitogglebuttonJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MitogglebuttonJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MitogglebuttonJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MitogglebuttonJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblToggle;
    private javax.swing.JToggleButton tbtnPrenderApagar;
    // End of variables declaration//GEN-END:variables
}
